#Requires -Version 5.1
<#
.SYNOPSIS
    Generates a stub SBOM (Software Bill of Materials) in SPDX JSON format.

.DESCRIPTION
    Reads manifest/dependencies.lock.json and VERSION to generate an updated
    sbom.spdx.json in the manifest directory.

    This is a stub implementation. For production use, integrate with a dedicated
    SBOM generation tool (e.g., Microsoft Sbom Tool, Syft, or CycloneDX).

.PARAMETER RepoRoot
    Repository root directory.
#>

[CmdletBinding()]
param(
    [Parameter()]
    [string]$RepoRoot
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$ScriptRoot = $PSScriptRoot
if (-not $RepoRoot) {
    $RepoRoot = Split-Path $ScriptRoot -Parent
}

function Write-Log {
    param([string]$Message, [string]$Severity = 'INFO')
    $ts = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    Write-Host "[$ts] [$Severity] $Message"
}

try {
    $versionFile = Join-Path $RepoRoot 'VERSION'
    $version = (Get-Content $versionFile -Raw).Trim()

    $lockFile = Join-Path $RepoRoot 'manifest\dependencies.lock.json'
    $lockContent = Get-Content $lockFile -Raw | ConvertFrom-Json
    $deps = $lockContent.Dependencies

    $timestamp = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
    $docNs = "https://github.com/markashook/enterpriseai/sbom/$version-$(Get-Date -Format 'yyyyMMddHHmmss')"

    $packages = @(
        @{
            SPDXID = 'SPDXRef-Package-EnterpriseAI'
            name = 'EnterpriseAI Local Runtime and Gateway'
            versionInfo = $version
            downloadLocation = 'https://github.com/markashook/enterpriseai'
            licenseConcluded = 'MIT'
            licenseDeclared = 'MIT'
            copyrightText = 'NOASSERTION'
        }
    )

    $props = $deps | Get-Member -MemberType NoteProperty | Select-Object -ExpandProperty Name
    foreach ($depName in $props) {
        $dep = $deps.$depName
        $packages += @{
            SPDXID = "SPDXRef-Package-$depName"
            name = $depName
            versionInfo = $dep.Version
            downloadLocation = if ($dep.DownloadUrl) { $dep.DownloadUrl } else { 'NOASSERTION' }
            licenseConcluded = if ($dep.License) { $dep.License } else { 'NOASSERTION' }
            licenseDeclared = if ($dep.License) { $dep.License } else { 'NOASSERTION' }
            copyrightText = 'NOASSERTION'
        }
    }

    $relationships = @(
        @{
            spdxElementId = 'SPDXRef-DOCUMENT'
            relationshipType = 'DESCRIBES'
            relatedSpdxElement = 'SPDXRef-Package-EnterpriseAI'
        }
    )
    foreach ($depName in $props) {
        $relationships += @{
            spdxElementId = 'SPDXRef-Package-EnterpriseAI'
            relationshipType = 'CONTAINS'
            relatedSpdxElement = "SPDXRef-Package-$depName"
        }
    }

    $sbom = @{
        SPDXID = 'SPDXRef-DOCUMENT'
        spdxVersion = 'SPDX-2.3'
        creationInfo = @{
            created = $timestamp
            creators = @("Tool: EnterpriseAI-Generate-Sbom")
            comment = "Stub SBOM generated by Generate-Sbom.ps1. Replace with dedicated SBOM tool output for production."
        }
        name = 'EnterpriseAI Local Runtime and Gateway'
        dataLicense = 'CC0-1.0'
        documentNamespace = $docNs
        packages = $packages
        relationships = $relationships
    }

    $sbomPath = Join-Path $RepoRoot 'manifest\sbom.spdx.json'
    $sbom | ConvertTo-Json -Depth 10 | Set-Content -Path $sbomPath -Encoding UTF8
    Write-Log "SBOM written to: $sbomPath"
    exit 0

} catch {
    Write-Log "SBOM generation failed: $($_.Exception.Message)" 'ERROR'
    exit 1
}
